Object.defineProperty(exports,"__esModule",{value:true});exports.publicAnonKey=exports.projectId=void 0;/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

var projectId=exports.projectId="tjzbmvkzbhbmckxuzsxs";
var publicAnonKey=exports.publicAnonKey="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqemJtdmt6YmhibWNreHV6c3hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0MzczMTgsImV4cCI6MjA3NjAxMzMxOH0.DfYdph8OFVBpq2DcTn-VUDWUWVaJp5yKkvoh5BsGbVw";