var _interopRequireDefault=require("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(exports,"__esModule",{value:true});exports.set=exports.mset=exports.mget=exports.mdel=exports.getByPrefix=exports.get=exports.del=void 0;var _asyncToGenerator2=_interopRequireDefault(require("@babel/runtime/helpers/asyncToGenerator"));











var _supabaseJs=require("jsr:@supabase/supabase-js@2.49.8");/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS *//* Table schema:
CREATE TABLE kv_store_4447fa50 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/// View at https://supabase.com/dashboard/project/tjzbmvkzbhbmckxuzsxs/database/tables
// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
var client=function client(){return(0,_supabaseJs.createClient)(Deno.env.get("SUPABASE_URL"),Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"));};// Set stores a key-value pair in the database.
var set=exports.set=/*#__PURE__*/function(){var _ref=(0,_asyncToGenerator2.default)(function*(key,value){
var supabase=client();
var _yield$supabase$from$=yield supabase.from("kv_store_4447fa50").upsert({
key:key,
value:value
}),error=_yield$supabase$from$.error;
if(error){
throw new Error(error.message);
}
});return function set(_x,_x2){return _ref.apply(this,arguments);};}();

// Get retrieves a key-value pair from the database.
var get=exports.get=/*#__PURE__*/function(){var _ref2=(0,_asyncToGenerator2.default)(function*(key){
var supabase=client();
var _yield$supabase$from$2=yield supabase.from("kv_store_4447fa50").select("value").eq("key",key).maybeSingle(),data=_yield$supabase$from$2.data,error=_yield$supabase$from$2.error;
if(error){
throw new Error(error.message);
}
return data==null?void 0:data.value;
});return function get(_x3){return _ref2.apply(this,arguments);};}();

// Delete deletes a key-value pair from the database.
var del=exports.del=/*#__PURE__*/function(){var _ref3=(0,_asyncToGenerator2.default)(function*(key){
var supabase=client();
var _yield$supabase$from$3=yield supabase.from("kv_store_4447fa50").delete().eq("key",key),error=_yield$supabase$from$3.error;
if(error){
throw new Error(error.message);
}
});return function del(_x4){return _ref3.apply(this,arguments);};}();

// Sets multiple key-value pairs in the database.
var mset=exports.mset=/*#__PURE__*/function(){var _ref4=(0,_asyncToGenerator2.default)(function*(keys,values){
var supabase=client();
var _yield$supabase$from$4=yield supabase.from("kv_store_4447fa50").upsert(keys.map(function(k,i){return{key:k,value:values[i]};})),error=_yield$supabase$from$4.error;
if(error){
throw new Error(error.message);
}
});return function mset(_x5,_x6){return _ref4.apply(this,arguments);};}();

// Gets multiple key-value pairs from the database.
var mget=exports.mget=/*#__PURE__*/function(){var _ref5=(0,_asyncToGenerator2.default)(function*(keys){var _data$map;
var supabase=client();
var _yield$supabase$from$5=yield supabase.from("kv_store_4447fa50").select("value").in("key",keys),data=_yield$supabase$from$5.data,error=_yield$supabase$from$5.error;
if(error){
throw new Error(error.message);
}
return(_data$map=data==null?void 0:data.map(function(d){return d.value;}))!=null?_data$map:[];
});return function mget(_x7){return _ref5.apply(this,arguments);};}();

// Deletes multiple key-value pairs from the database.
var mdel=exports.mdel=/*#__PURE__*/function(){var _ref6=(0,_asyncToGenerator2.default)(function*(keys){
var supabase=client();
var _yield$supabase$from$6=yield supabase.from("kv_store_4447fa50").delete().in("key",keys),error=_yield$supabase$from$6.error;
if(error){
throw new Error(error.message);
}
});return function mdel(_x8){return _ref6.apply(this,arguments);};}();

// Search for key-value pairs by prefix.
var getByPrefix=exports.getByPrefix=/*#__PURE__*/function(){var _ref7=(0,_asyncToGenerator2.default)(function*(prefix){var _data$map2;
var supabase=client();
var _yield$supabase$from$7=yield supabase.from("kv_store_4447fa50").select("key, value").like("key",prefix+"%"),data=_yield$supabase$from$7.data,error=_yield$supabase$from$7.error;
if(error){
throw new Error(error.message);
}
return(_data$map2=data==null?void 0:data.map(function(d){return d.value;}))!=null?_data$map2:[];
});return function getByPrefix(_x9){return _ref7.apply(this,arguments);};}();